name : Github Action  실행시켜 보기

on:
  push:
    branches:
      - main


jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps: #첫번째 스텝
      - name: Hello World 찍기
        run : echo "Hello World"

      - name: 여러 명령어 문장 작성
        run: |
          echo "Good"
          echo "Morning"
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to production
        run: echo "Deploying to production server..."
        # 여기에 실제 배포 명령어를 추가하세요.